### ISSUE TITLE
You are on the [Insert Plan Here] plan, paying Monthly...

### ISSUE THREAD

**Issue by 12thLetter** [hamiltoniot/contrib#6]
Whenever I access this page (from RSA of course so maybe its a latency thing) the page loads text behind the loading screen without the plan text. I get the text "You are on the plan, paying Monthly. Your plan will renew on 2018-02-01 for $."

Note the missing plan I'm on, as well as the value when renewal happens.

**Comment by immesys** [comment]
Should be fine now
